---
title: "Metadada druk op de biodiversiteit wereldwijd - Impact consumptie voeding en biomassa"
date: 2020-07-01T10:00:00
bibliography: ../references.bib
link-citations: TRUE
hoofdstuk: 4
thema:
  - Natuur & maatschappij
keywords:
  - voetafdruk
  - landvoetafdruk
  - consumptie
  - import
  - invoer
  - LCA
  - levenscyclusanalyse
  - mondiaal
  - wereld
  - biodiversiteitsverlies
  - biomassa
  - voeding
  - hout
  - papier
  - soja
  - rundsvlees
  - leder
  - rubber
  - koffie
  - cacao
  - palmolie

lang: nl
tab: metadata
verantwoordelijke:
- Katrijn Alaerts <katrijn.alaerts@inbo.be>
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)
library(git2rdata)
```
## Technische informatie
**Periodiciteit**: eenmalig
\- **Volgende update**: onbekend
\- **Databereik**: 2013 - 2017

## Databron
- **Producent**: Instituut voor Natuur- en Bosonderzoek
- **Dataset**: op basis van landvoetafdrukdata van @jennings_risky_2019 en omrekeningsfactoren voor biodiversiteitsverlies  uit  @chaudhary_land_2018
- **Gegevensinzameling**: De studie van @jennings_risky_2019 - in opdracht van WWF - richt zich op de Belgische invoer van zeven groepen van goederen die wereldwijd bekend staan om hun rol in ontbossing: hout en papier, rundsvlees en leder, soja, cacao, palmolie, koffie, natuurlijk rubber, en hun afgeleide producten. 
Ze analyseert **fysieke goederenstromen tussen landen**, uitgedrukt in ton of kubieke meter. 
Ze vertrekt van de invoer- en uitvoergegevens per land uit de databank van [UN COMTRADE](https://comtrade.un.org/). 
De wederuitvoer van de goederenstromen wordt in rekening gebracht: waar België grondstoffen en/of producten invoert uit een land A dat zelf de grondstoffen en/of producten importeert uit een land B (en C, enz.), worden de importgegevens van het land A gebruikt om de werkelijke herkomst te bepalen. 
Om die terugrekening haalbaar te houden, komen enkel landen die minstens 2% van de waarde van de Belgische invoer van een productgroep vertegenwoordigen aan bod.

  Voor rundsvlees en leder en hout en papier bekijkt de studie naast de invoer ook de Belgische binnenlandse productie. 
Die data komen uit de databank van [FAOSTAT](http://www.fao.org/faostat/en/#home). 
Voor elke productgroep wordt een schatting gemaakt van de hoeveelheid bestemd voor consumptie in België. 
Daarbij geldt: consumptie = invoer + binnenlandse productie - export.  

  Met behulp van opbrengstdata per gewas en per land (in ton of kubieke meter per hectare), afkomstig uit de [FAOSTAT](http://www.fao.org/faostat/en/#home)-databank, en gegevens over het aandeel van de goederen in verschillende consumptieproducten, berekent de studie de **landoppervlaktes die nodig zijn om onze consumptie en productie te ondersteunen**. 
Voor rundsvlees en leder telt alleen grasland mee als bron van diervoeder. Akkerbouwteelten die ook een grondstof vormen voor diervoeder (bv. soja) zitten niet mee in de cijfers vervat. 

  Voor hout en papier en rundsvlees en leder wijkt de berekening van de benodigde landoppervlakte af van die van de andere goederenstromen. 
Voor beide productgroepen zijn geen eenvoudige, wijd verspreide opbrengstdata beschikbaar om de ingezette hoeveelheid land in te schatten. 
Bossen kennen een erg verschillend beheer en hout wordt het hele jaar door geoogst op uiteenlopende manieren. 
De studie gebruikt data over de gemiddelde jaarlijkse aanwas (= de toename in het houtvolume per hectare en per jaar) van bossen, om de oppervlakte te berekenen die nodig is om een bepaald productievolume te bereiken. 
Om de opbrengst (i.e. toename in karkasgewicht) van vleesrunderen per oppervlakte grasland in te schatten, wordt de totale hoeveelheid grasland van een land toegekend aan de verschillende types van grazers. 
Dat gebeurt aan de hand van cijfers over de relatieve voederconversie-efficiëntie van elk grazertype en de totale productie van elke deelsector. 
Vleesrunderen geven twee producten: rundsvlees en leder. Het geassocieerde landgebruik wordt verdeeld over beide producten op basis van hun massa: de huid bedraagt zo’n 15% van de totale massa van het karkas en krijgt dus 15% van de landvoetafdruk toegekend.

  Aan de hand van een **risicoscore voor ontbossing per land** wordt de landvoetafdruk omgerekend naar een ‘landvoetafdruk met een hoog risico op ontbossing’. 
Die risicoscore is gebaseerd op de deelscores voor vier criteria: 
  + het verlies aan boombedekking: het verlies aan landoppervlakte met meer dan 10% boombedekking tussen 2012 en 2016 (data van [Global Forest Watch](https://data.globalforestwatch.org/)) 
  + de ontbossingssnelheid: de verandering in de netto oppervlakte van natuurlijk bos tussen 2010 en 2015 (data [FAO Forest Resources Assessment](http://www.fao.org/forest-resources-assessment/en/))
  + de perceptie van corruptie: de [Corruptie Perceptie Index 2017](https://www.transparency.org/en/news/corruption-perceptions-index-2017) van Transparency International
  + arbeidsnormen: de kans op ernstige overtredingen van de rechten van arbeiders aan de hand van de [Global Rights Index 2016](https://www.ituc-csi.org/IMG/pdf/survey_ra_2016_eng.pdf) van de International Trade Union Confederation.

## Berekeningswijze
Met de totale invoer en uitvoer per productgroep (gemiddelde over 5 jaar: 2013 - 2017), de binnenlandse productie en de geschatte consumptiecijfers wordt voor elke productgroep het gemiddelde aandeel van de invoer bestemd voor Belgische consumptie bepaald. 
Daarbij wordt verondersteld dat het aandeel consumptie in de invoer gelijk is aan het aandeel consumptie in de binnenlandse productie.
Dat gemiddelde aandeel wordt gebruikt om de gedetailleerde data van de landvoetafdruk van de Belgische invoer per productgroep, land en jaar (2013 - 2017) om te rekenen naar een gemiddelde **landvoetafdruk van de Belgische consumptie** per productgroep en land (gemiddelde over 5 jaar). 
Figuur 1 vat die data samen per productgroep.

Figuur 2 zoomt in op de 20 landen waar de landvoetafdruk van de Belgische consumptie het hoogst is. 
Met behulp van omrekeningsfactoren uit de levenscyclusanalyse worden de landoppervlaktes per productgroep en per land vertaald naar een **impact op het algemene verlies aan biodiversiteit**. 
Hier worden de meest recente omrekeningsfactoren gebruikt voor de drukfactor landgebruik, per productiesysteem en per land, zoals ze voortvloeien uit het levenscyclus-initiatief van UNEP-SETAC [@chaudhary_land_2018]. 
Die omrekeningsfactoren reflecteren het biodiversiteitsverlies per eenheid van druk, bijvoorbeeld per hectare intensief of extensief gebruikt akkerland of plantage. 
Ze houden rekening met het globale verlies aan soorten uit vijf verschillende taxonomische groepen (zoogdieren, vogels, amfibieën, reptielen en planten) en met de kwetsbaarheid van die soorten. 
Soorten die enkel in specifieke, geografisch begrensde gebieden voorkomen (endemische soorten) en meer bedreigde soorten volgens de *International Union for the Conservation of Nature* (IUCN) krijgen een hoger gewicht. 
Voor de omrekeningsfactoren gelden volgende aannames: hout en papier, palmolie, koffie, cacao en rubber worden geteeld op een “intensieve plantage”, rundsvlees en leder op “intensief grasland” en soja op “intensief akkerland”. 
Het berekende biodiversiteitsverlies in mondiale PDF wordt herschaald naar een waarde tussen 0 en 100.

## Opmerkingen bij de gegevenskwaliteit en betrouwbaarheid
De studie van @jennings_risky_2019 probeert de belangrijkste impact van de handel in de zeven productgroepen te vatten. 
Ze neemt, om praktische redenen, niet alle mogelijke producten en landen van herkomst mee. 
Veel van de berekeningen zijn, bij gebrek aan betere data, gebaseerd op ruwe, vaak conservatieve aannames. 
De resultaten vormen dus een eerste inschatting die naar alle waarschijnlijkheid de werkelijke impact onderschat. 
Specifieke tekortkomingen zijn o.a.:

* Veel van de bestudeerde goederen belanden in duizenden producten. De analyse focust enkel op de **hoofdproducten** voor elke goederenstroom. 
* De data over het **aandeel van de bestudeerde goederen in typische producten** zijn van lage kwaliteit. In veel producten worden de goederen gecombineerd met andere componenten, in verhoudingen die heel specifiek zijn voor elk product. De omrekeningsfactoren die gebruikt worden om het gehalte van een goed in een afgewerkt product te berekenen, zijn daarom erg onzeker. 
* Veel productieketens bestaan uit een reeks stappen en na elke stap kan het - deels afgewerkte - product uitgevoerd worden. Het **land van herkomst** van de bestudeerde goederen is voor sommige (complexere) producten dus moeilijk met zekerheid te bepalen.  
* De **opbrengstcijfers** voor de productgroepen hout en papier, en rundsvlees en leder zijn gebaseerd op erg ruwe inschattingen. 
* Voor rundsvlees en leder telt bovendien **alleen grasland mee als bron van diervoeder**. Akkerbouwteelten die ook een grondstof vormen voor diervoeder (bv. soja) zitten niet mee in de cijfers vervat. 
* De methode maakt gebruik van **data op landniveau**. Regionale verschillen in productiviteit, productienormen, ontbossingsrisico’s, enzovoort zijn niet meegenomen. Om de werkelijke impact van onze consumptie van goederen en diensten beter te kunnen inschatten, is een helder beeld nodig van de precieze locatie van de productie en van het aandeel producten dat voldoet aan duurzame productienormen die ook de biodiversiteit in rekening brengen. Methoden die toelaten om regionale en lokale verschillen in productienormen en biodiversiteitsverliezen te traceren zijn volop in ontwikkeling [bv. @escobar_spatially-explicit_2020; @green_linking_2019; @hoang_mapping_2021; @moran_identifying_2016; @trase_transparency_2020; @zu_ermgassen_origin_2020].

De **omrekeningsfactoren** die gebruikt worden om de landvoetafdruk om te zetten naar een maat voor **biodiversiteitsverlies** zijn gebaseerd op de best beschikbare data, maar zijn nog steeds erg onzeker [@chaudhary_land_2018]. 
Hoewel de gebruikte productiemethoden verschillen van land tot land en van streek tot streek kozen we in deze eerste benadering bij elke productgroep voor een omrekeningsfactor die de impact van een intensief productiesysteem typeert.

## Download
**Broncode indicator**: [d8_mondiale_biodiversiteit_impact_consumptie_voeding_biomassa.Rmd](../d8_mondiale_biodiversiteit_impact_consumptie_voeding_biomassa/d8_mondiale_biodiversiteit_impact_consumptie_voeding_biomassa.Rmd) 
- **Basisdata**: [landvoetafdruk_biomassagoederen.tsv](../d8_mondiale_biodiversiteit_impact_consumptie_voeding_biomassa/landvoetafdruk_biomassagoederen.tsv), [biodiversiteitsvoetafdruk_biomassagoederen.tsv](../d8_mondiale_biodiversiteit_impact_consumptie_voeding_biomassa/biodiversiteitsvoetafdruk_biomassagoederen.tsv)
- **Metadata basisdata**: [landvoetafdruk_biomassagoederen.yml](../d8_mondiale_biodiversiteit_impact_consumptie_voeding_biomassa/landvoetafdruk_biomassagoederen.yml), [biodiversiteitsvoetafdruk_biomassagoederen.yml](../d8_mondiale_biodiversiteit_impact_consumptie_voeding_biomassa/biodiversiteitsvoetafdruk_biomassagoederen.yml)

## Referenties
