on:
  push:
    branches:
      - main

name: render-publish

jobs:
  render-indicator:
    runs-on: ubuntu-latest
    name: render-publish
    steps:
      - uses: inbo/actions/render_nara@master
        with:
          token: ${{ secrets.pat }}
          publish: 1
